dist: focal
language: node_js

node_js:
  - 10

os:
  - linux

git:
  depth: 2

# before_install:
#   - npm install -g node-gyp
# - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --pure-lockfile

script:
  - bash ./build-setup.sh
  - yarn install --pure-lockfile
  - yarn build

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./release-setup.sh
  on:
    branch: master
# cache:
#   # timeout: 1200
#   yarn: true
