language: node_js

git:
  depth: 2

env: SH="docker exec -t guidu bash -c"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --pure-lockfile

script:
  - source ./build-setup.sh
  - bolt install --pure-lockfile
  - yarn build

deploy:
  provider: script
  script:
    - node ./build/releases/bin/build-releases.js version
    - git push https://${GH_TOKEN}@github.com/uidu-org/guidu.git HEAD:master > /dev/null 2>&1
    - yarn build:pkg
    - node ./build/releases/bin/build-releases.js publish --public
    - git push https://${GH_TOKEN}@github.com/uidu-org/guidu.git --tags > /dev/null 2>&1
  on:
    branch: master

cache: yarn
