project_id: '459032'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /packages/**/*/lang/en.json
    translation: /%original_path%/%two_letters_code%.json
