name: Deploy Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Bundle app
        run: yarn build

      - name: Build Content
        run: bash ./build-setup.sh

      - name: Release Content
        run: bash ./release-setup.sh
