name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '14' ]
    name: Node ${{ matrix.node }} sample
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --pure-lockfile

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Build Content
        run: bash ./build-setup.sh
      - name: Release Content
        run: bash ./release-setup.sh
