name: Deploy Production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
          with:
            fetch-depth: 2

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Bundle app
        run: yarn build

      - name: Build Content
        run: bash ./build-setup.sh

      - name: Release Content
        run: bash ./release-setup.sh
