name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check-out repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --pure-lockfile

      - name: Bundle app
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Build Content
        run: bash ./build-setup.sh

      - name: Release Content
        run: bash ./release-setup.sh
